### PR TITLE
Update to wasmtime 22.0.0

### LINKED ISSUE #306: Bump wasmtime to v20.x
New wasmtime version was released a few days ago - https://github.com/bytecodealliance/wasmtime/releases/tag/v20.0.0

I'll take a crack at doing this myself if it's something that would be accepted.

### PR DESCRIPTION
**Pull request by jsturtevant**
Updates the package to use the latest wasmtime release

fixes #306

### CODE REVIEW

**Comment by jsturtevant** [comment]
Looks like there are a few other issues that we are working through #315

**Comment by jsturtevant** [comment]
will do after #316

**Comment by jsturtevant** [comment]
@kpreisser if this looks good, we can cut the release

**Review by kpreisser — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
