### PR TITLE
Add linux-arm64 and osx-arm64 runtimes to package.

### LINKED ISSUE #135: Error running libwasmtime on M1 Mac
When trying to consume `wasmtime-dotnet`, I get an error trying to load a module.  This works on my other machines, but not the M1 MacBook Pro.

```
System.DllNotFoundException : Unable to load shared library 'wasmtime' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libwasmtime, 0x0001): tried: 'libwasmtime' (no such file)
```

Upstream `wasmtime` publishes an artifact for macos aarch64.  Can `wasmtime-dotnet` publish that?

### PR DESCRIPTION
**Pull request by peterhuene**
This PR adds the wasmtime libraries for the following RIDs to the
`Wasmtime` package:

* linux-arm64
* osx-arm64

Fixes #135.

### CODE REVIEW

**Review by willhausman — APPROVED** [review]
@peterhuene I can successfully run `dotnet test Wasmtime.sln` on my M1.  It is probably worth seeing if a similar config can be added to the automated tests.

**Comment by peterhuene** [comment]
Unfortunately GitHub doesn't yet have hosted M1 runners (as far as I am aware), only support for self-hosted runners which we don't have the infrastructure for, currently.

**Comment by peterhuene** [comment]
@willhausman thanks again for reporting the issue and testing the fix!

As Wasmtime 0.40.0 will release soon, I'm going to wait until it does before pushing a `Wasmtime` package with the arm64 artifacts, if that's okay with you.

**Comment by willhausman** [comment]
@peterhuene Thanks. Do you know when 0.40.0 will release? I'm trying to make the transition to M1 as my daily driver, but my project can't run right now. I do have some leeway, though.

**Comment by peterhuene** [comment]
I think in another week or two. I'm happy to create a new "preview2" release just with the aarch64 artifacts if that helps you.

**Comment by willhausman** [comment]
2 weeks might be pushing it for me. If it is not an inconvenience, I would greatly appreciate a preview2 release.

**Comment by peterhuene** [comment]
@willhausman I've published `0.39.1-preview2` which should have support for `osx-arm64`. Please let me know if you run into any issues with it.

**Pull request merged**
