### PR TITLE
Added `ToString` method for `Mutability` struct

### PR DESCRIPTION
**Pull request by martindevans**
Added `ToString` method for `Mutability` struct

### CODE REVIEW

**Comment by martindevans** [comment]
It looks like the CI test runner crashed, I'm not sure why. Tests pass locally.

**Comment by peterhuene** [comment]
I suspect we need to sync to https://github.com/bytecodealliance/wasmtime/pull/5683.

Unrelated to the crash, CI's been flaky on Windows for an unknown reason (occasionally fails to download the wasmtime tarballs from GitHub).

I'll see about getting CI fixed shortly.

**Comment by peterhuene** [comment]
I put up #221 to fix CI; we can merge that and then rebase this PR on top.

**Review by peterhuene — APPROVED** [review]

**Comment by peterhuene** [comment]
If we rebase this, I'll merge with a (mostly) green CI.

This and the other PR will go into the 7.0.0 release, unfortunately, unless you really need me to backport either to the 6.0 release which is imminent.

**Comment by martindevans** [comment]
Rebased onto main.

> go into the 7.0.0 release

That's fine, neither are critical on my end :)

**Pull request merged**
